###
POST http://localhost:3006/api/routes/
Content-Type: application/json

{
    "name": "Luanda para Benguela",
    "source": {
        "lat": 1,
        "lng": 1
    },
    "destination": {
        "lat": 1,
        "lng": 1
    }
}

###
GET http://localhost:3006/api/routes/